stages: 
  - build
  - pack
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - nuget/

build:
  image: microsoft/dotnet:2.0.0-sdk
  stage: build
  script:
    - 'dotnet build'
  except: 
    - tags

build-and-pack-beta: 
  image: microsoft/dotnet:2.0.0-sdk
  stage: pack
  script:
    - 'dotnet pack -c Release -o ./nuget --version-suffix "beta" /p:Version=$CI_COMMIT_TAG'
  artifacts:
    paths:
      - ./nuget
  only:
    - tags
  except:
    - master@cosmic9studios/SlackApi

build-and-pack-prod: 
  image: microsoft/dotnet:2.0.0-sdk
  stage: pack
  script:
    - 'dotnet pack -c Release -o ./nuget /p:Version=$CI_COMMIT_TAG'
  artifacts:
    paths:
      - ./nuget
  only:
    - master@cosmic9studios/SlackApi
    - tags

publish: 
  image: microsoft/dotnet:2.0.0-sdk
  stage: publish
  variables:
    GIT_STRATEGY: none
  script: 
    - 'dotnet nuget push ./nuget/SlackApi.NetCore.*.nupkg -k $NUGET_KEY -s nuget.org'
  when: manual
  allow_failure: false
  only:
    - tags