variables: 
  VERSION: $CI_COMMIT_TAG
  VERSION_SUFFIX: beta
  NUPKG_PATH: ./nuget/SlackApi.NetCore.*.nupkg

include: 
 - 'https://gitlab.com/cosmic9studios/deployment/raw/master/jobs/nuget/pack_with_suffix.yml'
 - 'https://gitlab.com/cosmic9studios/deployment/raw/master/jobs/nuget/pack.yml'
 - 'https://gitlab.com/cosmic9studios/deployment/raw/master/jobs/nuget/publish_package.yml'
 - 'https://gitlab.com/cosmic9studios/deployment/raw/master/pipelines/nuget/pack_and_publish.yml'