# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: Api-Keys 


steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: pack
    configuration: '$(buildConfiguration)'
    packagesToPack: 'SlackApi.NetCore.csproj'
    versioningScheme: byPrereleaseNumber
    majorVersion: '2'
    minorVersion: '0'
    patchVersion: '0'
  
- script: dotnet nuget push *.nupkg -k $(NUGET_KEY) -s nuget.org
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    
    
    